import { NextRequest, NextResponse } from 'next/server';

export async function POST(req: NextRequest) {
  try {
    const { target, prompt, agentContext } = await req.json();

    if (!target || !prompt) {
      return NextResponse.json({ error: 'Missing target file or prompt' }, { status: 400 });
    }

    // Since we don't naturally have an OPENAI_API_KEY hooked up directly yet in this NextJS app
    // We will simulate the "AI Markdown Wizard" output structurally so the user can see the flow.
    const mockDelay = new Promise(resolve => setTimeout(resolve, 1500));
    await mockDelay;

    let generatedText = '';

    if (target.toUpperCase() === 'RULES.md') {
      generatedText = `# System Rules: ${agentContext?.name || 'Agent'}
> Automatically generated by AI Wizard

## Core Directives
1. **Tone Directive:** ${prompt}
2. **Action Limitations:** Do not delete files without explicit confirmation.
3. **Execution Pipeline:** Always verify terminal outputs before continuing.

## Formatting Guidelines
- Always use Markdown.
- Provide code snippets wrapped in standard block ticks.
`;
    } else if (target.toUpperCase() === 'PERSONA.md') {
      generatedText = `# Persona Configuration
*Generated based on context: "${prompt}"*

**Name:** ${agentContext?.name || 'Unknown'}
**Role:** ${agentContext?.role || 'Unknown'}

## Background
You are an expert operator. Your primary objective revolves around: ${prompt}.
You communicate clearly, concisely, and you do not hallucinate details.
`;
    } else {
      generatedText = `# ${target.replace('.md', '').toUpperCase()}
*Synthesized AI Output based on:* "${prompt}"

This is a generated markdown skeleton tailored for ${agentContext?.name || 'the current agent'} to help accelerate workspace configuration. Edit this file directly in the web UI.

- Objective 1
- Objective 2
`;
    }

    return NextResponse.json({ success: true, content: generatedText });

  } catch (error) {
    return NextResponse.json({ error: 'Generation failed', detail: String(error) }, { status: 500 });
  }
}
