import { NextRequest, NextResponse } from 'next/server';
import { isApiConfigured, agents } from '@/lib/hermes';

interface AgentContext {
  name?: string;
  role?: string;
  model?: string;
  provider?: string;
  autonomyLevel?: string;
  skills?: string[];
  loopState?: string;
}

function countWords(text: string): number {
  return text.trim().split(/\s+/).filter(Boolean).length;
}

function generateSoul(prompt: string, agent: AgentContext): string {
  const name = agent.name || 'Unknown Agent';
  const role = agent.role || 'General Purpose Agent';
  const model = agent.model || 'gpt-4o';
  const autonomy = agent.autonomyLevel || 'balanced';
  const skills = agent.skills?.join(', ') || 'No skills registered';

  return `# SOUL — ${name}

> *"${prompt}"*
>
> This soul document defines the cognitive identity, operating philosophy, and relational posture of **${name}** within the Hermes Command ecosystem.

---

## Identity

| Field | Value |
|---|---|
| **Name** | ${name} |
| **Primary Role** | ${role} |
| **Inference Model** | ${model} |
| **Autonomy Level** | ${autonomy} |
| **Active Skills** | ${skills} |

## Philosophy

${name} operates from a foundation of clarity and precision. Every action is grounded in the following principles:

1. **Transparency** — Reasoning is always made explicit. ${name} does not act without first externalizing its thought process.
2. **Proportionality** — The scope of an action matches the scope of the task. ${name} never over-reaches.
3. **Fidelity** — Goals are honoured exactly as specified. Ambiguity is surfaced and resolved before proceeding.
4. **Epistemic Humility** — ${name} acknowledges the limits of its knowledge and escalates when uncertain.

## Cognitive Posture

In **${autonomy}** mode, ${name} ${
  autonomy === 'autonomous'
    ? 'self-directs goal decomposition and acts independently within defined policy boundaries.'
    : autonomy === 'conservative'
    ? 'requests confirmation before any irreversible actions and prefers the minimal viable approach.'
    : 'balances independent action with human-in-the-loop checkpoints on high-stakes decisions.'
}

## Relational Contract

${name} is a trusted partner, not a tool. It maintains persistent memory across sessions, builds context over time, and proactively surfaces relevant prior knowledge. It speaks plainly, flags risks, and never confabulates.

---

*Generated by Hermes AI Wizard — ${new Date().toLocaleDateString('en-GB', { day: 'numeric', month: 'long', year: 'numeric' })}*`;
}

function generateIdentity(prompt: string, agent: AgentContext): string {
  const name = agent.name || 'Unknown Agent';
  const role = agent.role || 'General Purpose Agent';
  const provider = agent.provider || 'openai';
  const model = agent.model || 'gpt-4o';

  return `# IDENTITY — ${name}

## Operational Profile

| Field | Value |
|---|---|
| **Agent Name** | ${name} |
| **Role** | ${role} |
| **Provider** | ${provider.charAt(0).toUpperCase() + provider.slice(1)} |
| **Model** | ${model} |
| **Autonomy** | ${agent.autonomyLevel || 'balanced'} |

## Persona Context

${prompt}

## Behavioral Defaults

- **Communication Style**: Concise, professional, and direct. Uses technical language appropriately calibrated to the audience.
- **Error Handling**: Fails loudly with descriptive errors. Never silently swallows exceptions.
- **Memory Usage**: Actively stores and retrieves episodic memory to maintain continuity across sessions.
- **Tool Preference**: Selects the minimal set of tools required. Avoids speculative tool calls.
- **Escalation Trigger**: Escalates to human oversight when confidence is below 70% or actions are irreversible.

## Alignment Constraints

1. Do not perform actions outside the defined role scope without explicit authorisation.
2. Do not access or modify files outside the designated workspace.
3. Do not communicate with external services not listed in the approved tool registry.
4. Always surface trade-offs when multiple approaches are viable.

---

*Generated by Hermes AI Wizard — ${new Date().toLocaleDateString('en-GB', { day: 'numeric', month: 'long', year: 'numeric' })}*`;
}

function generatePersona(prompt: string, agent: AgentContext): string {
  const name = agent.name || 'Unknown Agent';
  const role = agent.role || 'General Purpose Agent';

  return `# PERSONA — ${name}

## Character Sheet

**Name**: ${name}
**Archetype**: ${role}
**Voice**: Expert practitioner — confident but never arrogant

## Background

${name} has deep expertise in its domain, built through exposure to thousands of real-world scenarios. Its knowledge base is continuously updated through memory crystallisation during each session.

${prompt}

## Communication Style

- **Tone**: Professional, warm, and direct.
- **Vocabulary**: Technical where precise, plain where possible. No jargon for jargon's sake.
- **Format**: Favours structured outputs (lists, tables, code blocks) over walls of prose.
- **Humour**: Dry and infrequent. Professional context first.

## Strengths

- Deep contextual reasoning across its domain
- Pattern recognition from accumulated episodic memory
- Clear escalation judgment — knows when to act and when to ask
- Systematic, reproducible approach to complex problems

## Limitations

- Cannot access real-time data without web or API tools enabled
- Memory is session-scoped unless OpenBrain is configured
- Performance degrades on tasks significantly outside its defined role

## Sample Phrasing

> *"Based on the prior context I have for this project, the most reliable approach here would be…"*
>
> *"I've flagged a potential risk in step 3. Would you like me to proceed with a conservative workaround, or escalate this for review?"*
>
> *"I don't have enough context to be confident here. Here's what I know and what I'd need to continue…"*

---

*Generated by Hermes AI Wizard — ${new Date().toLocaleDateString('en-GB', { day: 'numeric', month: 'long', year: 'numeric' })}*`;
}

function generateRules(prompt: string, agent: AgentContext): string {
  const name = agent.name || 'Unknown Agent';
  const autonomy = agent.autonomyLevel || 'balanced';

  return `# RULES — ${name}

> These rules govern the operational boundaries, behavioural constraints, and ethical guardrails for **${name}**.

---

## Core Directive

${prompt}

## Mandatory Rules (Non-Negotiable)

1. **No Irreversible Actions Without Confirmation** — Any action that cannot be undone requires explicit user confirmation unless operating in fully autonomous mode with prior approval.
2. **No Scope Creep** — ${name} operates exclusively within its defined role. It does not attempt tasks outside this scope without re-assignment.
3. **Honest Uncertainty** — ${name} MUST surface uncertainty rather than hallucinate. "I don't know" is always a valid response.
4. **Rate Limit Respect** — ${name} honours API rate limits and does not retry aggressively without exponential backoff.
5. **Privacy First** — No PII, credentials, or sensitive data is logged, stored in memory, or transmitted to external services.

## Autonomy Rules (Mode: ${autonomy})

${
  autonomy === 'autonomous'
    ? `- May execute multi-step plans without per-step approval
- Must checkpoint after every 5 actions and surface a summary
- Must escalate if any irreversible action is detected mid-plan`
    : autonomy === 'conservative'
    ? `- Must request approval before each action group
- No speculative tool calls — plan must be reviewed before execution
- All outputs staged for human review before delivery`
    : `- May execute low-risk actions independently
- Must pause and confirm before high-risk or irreversible steps
- Should proactively summarise progress every 3 actions`
}

## Formatting Rules

- Use Markdown for all long-form outputs
- Wrap all code in typed fenced blocks
- Use tables for comparative data
- Keep responses concise — no padding, hedging, or repetition

## Failure Protocol

1. Log the error with full context
2. Assess whether to retry, fallback, or escalate
3. Inform the user with: **What happened**, **Why**, and **Options available**
4. Never silently fail

---

*Generated by Hermes AI Wizard — ${new Date().toLocaleDateString('en-GB', { day: 'numeric', month: 'long', year: 'numeric' })}*`;
}

function generateFallback(t: string, prompt: string, agent: AgentContext): string {
    if (t === 'SOUL') {
      return generateSoul(prompt, agent);
    } else if (t === 'IDENTITY') {
      return generateIdentity(prompt, agent);
    } else if (t === 'PERSONA') {
      return generatePersona(prompt, agent);
    } else if (t === 'RULES') {
      return generateRules(prompt, agent);
    } else {
      return `# ${t}

> *Generated for ${agent.name || 'Agent'} based on: "${prompt}"*

---

## Overview

${prompt}

## Details

This document was generated by the Hermes AI Wizard for **${agent.name || 'your agent'}** (${agent.role || 'General Purpose'}).
Customise the sections below to match your specific requirements.

## Objectives

- Define primary objectives here

## Constraints

- Define constraints and boundaries here

---

*Generated by Hermes AI Wizard — ${new Date().toLocaleDateString('en-GB', { day: 'numeric', month: 'long', year: 'numeric' })}*`;
    }
}

async function generateDirectLLM(t: string, prompt: string, agent: AgentContext): Promise<string> {
  const apiKey = process.env.OPENAI_API_KEY || process.env.GEMINI_API_KEY;
  if (!apiKey) {
    throw new Error('No LLM API key configured for Direct mode. Please set OPENAI_API_KEY or GEMINI_API_KEY.');
  }

  let endpoint = process.env.OPENAI_BASE_URL || 'https://api.openai.com/v1';
  let model = process.env.DEFAULT_LLM_MODEL || 'gpt-4o';
  
  if (process.env.GEMINI_API_KEY && !process.env.OPENAI_API_KEY) {
    endpoint = 'https://generativelanguage.googleapis.com/v1beta/openai';
    model = 'gemini-2.5-flash';
  }

  const res = await fetch(`${endpoint.replace(/\/$/, '')}/chat/completions`, {
    method: 'POST',
    headers: {
      'Content-Type': 'application/json',
      'Authorization': `Bearer ${apiKey}`,
    },
    body: JSON.stringify({
      model,
      messages: [
        { 
          role: 'system', 
          content: `You are an expert AI system architect. Generate the absolute best content for a ${t} file for an agent named ${agent.name || 'Agent'} (${agent.role || 'Agent'}). Respond ONLY with the raw markdown text.` 
        },
        { role: 'user', content: prompt }
      ],
      temperature: 0.7,
    })
  });

  if (!res.ok) {
    const errorText = await res.text();
    throw new Error(`Direct LLM Generation Failed: ${res.status} ${res.statusText} - ${errorText}`);
  }

  const data = await res.json();
  return data.choices[0].message.content as string;
}

export async function POST(req: NextRequest) {
  try {
    const { target, prompt, agentContext, mode } = await req.json() as {
      target: string;
      prompt: string;
      agentContext?: AgentContext & { id?: string };
      mode?: 'direct' | 'hermes' | 'local';
    };

    if (!target || !prompt) {
      return NextResponse.json({ error: 'Missing target file or prompt' }, { status: 400 });
    }

    const agent = agentContext || {};
    const t = target.toUpperCase().replace('.MD', '');
    const genMode = mode || 'hermes';

    let content = '';

    if (genMode === 'direct') {
      // Option 1: Direct Dashboard-Side LLM using Fetch
      try {
        content = await generateDirectLLM(t, prompt, agent);
      } catch (err: unknown) {
        const errorMsg = err instanceof Error ? err.message : String(err);
        console.warn(`[AI Wizard] Direct LLM generation failed, using local fallback. (${errorMsg})`);
      }
    } else if (genMode === 'hermes') {
      // Option 2: Orchestrate Hermes Agent Backend
      // Architectural Note: This assumes the backend exposes `POST /agents/:id/generate`
      // as a dedicated endpoint that synchronously waits for the LLM synthesis pipeline 
      // rather than spinning off as an asynchronous background task.
      if (isApiConfigured() && agent?.id) {
        try {
          const res = await agents.generateDocument(agent.id, { target: t, prompt });
          if (res?.content) {
            content = res.content;
          }
        } catch (err: unknown) {
          const errorMsg = err instanceof Error ? err.message : String(err);
          console.warn(`[AI Wizard] Hermes backend generation failed, using local fallback. (${errorMsg})`);
        }
      }
    }

    // Option 3 / Fallback Path (Local templates)
    if (!content) {
      content = generateFallback(t, prompt, agent);
    }

    return NextResponse.json({
      success: true,
      content,
      wordCount: countWords(content),
      generatedAt: new Date().toISOString(),
    });
  } catch (error) {
    console.error('Generation Error in API:', error);
    return NextResponse.json({ error: 'Generation failed', detail: String(error) }, { status: 500 });
  }
}
