/**
 * /api/agents/soul — Agent cognitive identity (SOUL document)
 * Replaces: fs.readFile(AGENTS_DIR/agentId/SOUL.md) → hermes/agents + memory
 */
import { NextResponse } from 'next/server';
import { agents, memory } from '@/lib/hermes';

export async function GET(req: Request) {
  try {
    const { searchParams } = new URL(req.url);
    const agentId = searchParams.get('agentId');
    if (!agentId) return NextResponse.json({ error: 'agentId required' }, { status: 400 });

    const [agent, agentMemories] = await Promise.all([
      agents.getAgent(agentId),
      memory.getMemories(agentId),
    ]);

    // Build a dynamic SOUL document from Hermes agent data
    const soulContent = `# SOUL — ${agent.name} (${agent.emoji})

**Role**: ${agent.role}
**Model**: ${agent.model}
**Autonomy**: ${agent.autonomyLevel}
**Status**: ${agent.status}

## Cognitive Profile

This agent operates in **${agent.autonomyLevel}** mode within the Hermes cognitive framework.
It maintains ${agentMemories.length} memory entries across episodic, semantic, procedural, and reflective domains.

## Active Goals
${agent.goals.length > 0
  ? agent.goals.map(g => `- [${g.status.toUpperCase()}] ${g.title} (${g.progress}%)`).join('\n')
  : '_No active goals. Assign goals from the Goals tab._'
}

## Skills
${agent.skills.length > 0
  ? agent.skills.map(s => `- ${s}`).join('\n')
  : '_No skills registered. Enable skills from the Skills & MCP tab._'
}

---
*Soul document auto-generated by Hermes Command v1.0.0*
`;

    return NextResponse.json({
      content: soulContent,
      agent: {
        id: agent.id,
        name: agent.name,
        emoji: agent.emoji,
        role: agent.role,
        model: agent.model,
        autonomyLevel: agent.autonomyLevel,
        loopState: agent.loopState,
      },
    });
  } catch (error) {
    return NextResponse.json({ error: String(error) }, { status: 500 });
  }
}

export async function PUT(req: Request) {
  try {
    const { searchParams } = new URL(req.url);
    const agentId = searchParams.get('agentId');
    if (!agentId) return NextResponse.json({ error: 'agentId required' }, { status: 400 });

    const body = await req.json();

    // Update agent identity fields
    const updated = await agents.updateAgent(agentId, {
      role: body.role,
      model: body.model,
      autonomyLevel: body.autonomyLevel,
    });

    return NextResponse.json({ ok: true, agent: updated });
  } catch (error) {
    return NextResponse.json({ error: String(error) }, { status: 500 });
  }
}
